### ISSUE TITLE
`update` replaces entire entry

### ISSUE THREAD

**Issue by chetbox** [victorquinn/dynasty#48]
`.update` is currently a synonym for `.insert` which replaces an entry with the associated key. `.update` should use DynamoDB's `UpdateItem`, not `PutItem`.

e.g.
```javascript
var my_table = dynasty.table('my_table);

my_table.insert({
  id: 5, // The hash key of the table
  name: 'An ietm',
  description: 'A thing'
})
.then(function() {
  my_table.update({
    id: 5,
    name: 'An item'
});
```

This leaves you with an entry lacking the `description` field.

**Comment by KRSogaard** [comment]
I am also having this problem

**Comment by Vuuo** [comment]
```javascript
var _topics = dynamodb_client.table('my_topics');
_topics.update({
  id: 1234,
  last_50_posts: ['a', 'b', 'c']     
})
```
And I get this error msg:
```
Unhandled rejection MultipleValidationErrors: There were 2 validation errors:
* MissingRequiredParameter: Missing required key 'Key' in params
* UnexpectedParameter: Unexpected key 'Item' found in params
```

**Comment by victorquinn** [comment]
Arg, whoops I'm seeing the issue too @Vuuo , working on a fix now!

**Comment by victorquinn** [comment]
Ok @Vuuo I just pushed an update to Dynasty (0.2.0) which fixes the issue.

Note the minor version bump as the API for `.update()` changed slightly. The new API is [on the docs page](http://dynastyjs.com/#update), but basically it expects at least 2 arguments, the first being the key of the item to update and the second being an object representing the keys/values to update. This was necessary make things work as the core AWS library needs.

**Comment by Vuuo** [comment]
Awesome!

**Comment by ruandre** [comment]
I'm still having this issue on 0.2.4

Simple test code:
```js
var cfg     = require('./config.js')
var dynasty = require('dynasty')(cfg.dbCreds)
var table   = dynasty.table('test')

table
  .update('testing', {
    test: {
      'xyz': 'abc'
    }
  })
  .then(function(awsResp) {
    console.log(awsResp)
  })
```

Database item **before**:
```js
{
  "id": "testing",
  "test": {
    "one": 1,
    "two": 2
  }
}
```

Database item **after**:
```js
{
  "id": "testing",
  "test": {
    "xyz": "abc"
  }
}
```
